# Generated by Django 4.2.6 on 2023-10-28 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_newsauthor_name'), ('core', '0003_alter_newsarticle_headline'), ('core', '0004_alter_newsarticle_date_published'), ('core', '0005_account_interest_rate'), ('core', '0006_newsarticle_body_newsarticle_preview'), ('core', '0007_customer_remove_account_account_holder_and_more'), ('core', '0008_customer_security_candy'), ('core', '0009_customer_joined_date'), ('core', '0010_alter_customer_customer_id'), ('core', '0011_remove_account_interest_rate_and_more'), ('core', '0012_rename_referrer_customer_id_customer_referrer'), ('core', '0013_receiptprinter'), ('core', '0014_alter_customer_costume_alter_customer_first_name_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=128, unique=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.newsauthor')),
                ('body', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='TBA', max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Edween', max_length=64)),
                ('costume', models.CharField(default='Founder', max_length=64)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('security_candy', models.CharField(default='', max_length=64)),
                ('joined_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AnchorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
