# Generated by Django 4.2.6 on 2023-10-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_newsauthor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
