# Generated by Django 4.2.6 on 2023-10-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newsarticle_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
