# Generated by Django 4.2.6 on 2023-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
