# Generated by Django 4.2.6 on 2023-10-19 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_security_candy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
