# Generated by Django 4.2.6 on 2023-10-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_anchor_event_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_anchor_event_timestamp',
        ),
        migrations.CreateModel(
            name='AnchorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
