# Generated by Django 4.2.6 on 2023-10-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_account_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='referrer_customer_id',
            new_name='referrer',
        ),
    ]
