# Generated by Django 4.2.6 on 2023-10-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_referrer_customer_id_customer_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
