# Generated by Django 4.2.6 on 2023-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_receiptprinter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='costume',
            field=models.CharField(default='Founder', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Edween', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='security_candy',
            field=models.CharField(default='', max_length=64),
        ),
    ]
