# Generated by Django 4.2.6 on 2023-10-29 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0014_alter_customer_costume_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='anchorevent',
            name='category',
            field=models.CharField(choices=[('CREATE_ACCOUNT', 'Create the account.'), ('DEPOSIT', 'Deposit funds into the associated account.'), ('WITHDRAWAL', 'Withdraw funds from the associated account.'), ('UPDATE_INTEREST', 'Update the interest rate of the associated account.')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='anchorevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
