# Generated by Django 4.2.6 on 2023-10-29 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_account_account_name_alter_anchorevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
