# Generated by Django 4.2.6 on 2023-10-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_account_account_name_alter_anchorevent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eek_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='eek_level',
            field=models.IntegerField(default=0),
        ),
    ]
