# Generated by Django 4.2.6 on 2023-10-29 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_anchorevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
