# Generated by Django 4.2.6 on 2023-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bankstate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstate',
            name='customer_referral_reward_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bankstate',
            name='new_customer_starting_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bankstate',
            name='new_customer_starting_interest_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
