# Generated by Django 4.2.6 on 2023-10-31 12:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bankstate_customer_referral_reward_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCardPrintJob',
            fields=[
                ('job_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=core.models.get_current_utc_timestamp)),
                ('debit_card_file_bytes', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IdCardPrintJob',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankstate',
            name='customer_referral_reward_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankstate',
            name='new_customer_starting_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=2.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankstate',
            name='new_customer_starting_interest_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
