# Generated by Django 4.2.6 on 2023-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_debitcardprintjob_delete_idcardprintjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
